### REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "test@mail.com",
  "name": "Test",
  "password": "password123"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "password123"
}

### REFRESH
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoidGVzdEBtYWlsLmNvbSIsImlhdCI6MTc3OTU1NzkyMSwiZXhwIjoxNzgwMTYyNzIxfQ.E0h26nOlf1RzaSO1xU1xCCHKAHopuRXjI2VEm433ZLU"
}

### LOGOUT
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoidGVzdEBtYWlsLmNvbSIsImlhdCI6MTc3OTU1ODA5OCwiZXhwIjoxNzc5NTU4OTk4fQ.6JgaGiLN3tX0iIZ7Zpd9uJRTKc-nKnwYDNq523LrFJM

### USER 
POST http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoidGVzdEBtYWlsLmNvbSIsImlhdCI6MTc3OTU1ODIyNCwiZXhwIjoxNzc5NTU5MTI0fQ.vSvOhtnE_F2QgBVfqiVFVN5EOTQIoAOdw-GInVTzGvs