### REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "chris01@gmail.com",
  "password": "123456",
  "name": "Chris"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "chris01@gmail.com",
  "password": "123456"
}